name: Run Command on Ubuntu

on: [push]

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run command
        run: git clone https://github.com/beefproject/beef && cd beef && ./install 
